//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.Web {
    
    public partial class DashBoardModules {
        protected System.Web.UI.HtmlControls.HtmlForm frmDashboardModule;
        protected UAL.Web.UserManagement.DualList dashboardDualList;
        protected Framework.Controls.RollOverButton rollBtnSave;
        protected Framework.Controls.RollOverButton rollBtnCancel;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidListBoxCollection;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hidIsPanelVisible;
    }
}
