//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAL.Web {
    
    public partial class GadgetControl {
        protected System.Web.UI.HtmlControls.HtmlImage imgPrefernce;
        protected System.Web.UI.WebControls.ImageButton imgRemove;
    }
}
