<%@ Page language="c#" Codebehind="TermsAndConditions.aspx.cs" AutoEventWireup="false" Inherits="UAL.Web.TermsAndConditions" %>
<form runat="server" id="frmDefault">
	<br>
	<TABLE align="center" id="Table1" cellSpacing="1" cellPadding="1" width="98%" border="0">
		<TR>
			<td align="left" class="UAl-text-small"><strong> ATTENTION: PLEASE READ ALL THESE 
					PROVISIONS ("TERMS") CAREFULLY BEFORE USING THIS WEB SITE. USING THIS WEB SITE 
					INDICATES YOUR AGREEMENT AND ACCEPTANCE OF THESE TERMS. IF YOU DO NOT ACCEPT 
					THESE TERMS, DO NOT USE THIS WEB SITE OR DOWNLOAD MATERIALS FROM THIS SITE.</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> The Site and its Use</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				The United Aluminium web site is owned and provided by United Aluminium (UAL) 
				from its offices in the State of Connecticut. The applicable web site or sites 
				are referred to herein as the "Site." Your access to and use of the Site is 
				subject to these Terms and all applicable laws.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				You shall use the Site for lawful purposes only. You shall not post or transmit 
				through the Site any information or material which violates or infringes, in 
				any way, the rights of others, or which is unlawful, threatening, abusive, 
				defamatory, invasive of privacy or publicity rights, vulgar, obscene, profane, 
				harassing, or otherwise objectionable. Nor shall you post or transmit through 
				the Site any information or material which encourages conduct that would 
				constitute a criminal offense, give rise to liability or otherwise violate any 
				law or administrative ruling or guidelines, is in violation of these Terms, or 
				which, without UAL prior written approval, contain advertising or any 
				solicitation with respect to products or services. Any conduct by you that, in 
				UAL’s opinion, restricts or inhibits any other user from using or accessing the 
				Site will not be permitted.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				The Site contains information and materials, including but not limited to, 
				text, software and graphics (collectively "Materials") which are derived in 
				whole or in part from information and materials supplied by UAL, and are 
				protected by international copyright, trademark and other laws and the entire 
				content of the Site is copyrighted as a collective work under the United States 
				Copyright Laws. Materials may not be copied, reproduced, republished, modified, 
				uploaded, posted, transmitted or distributed in any way or decompiled, reverse 
				engineered or disassembled, including but not limited to the text, images as 
				well as any software (including but not limited to any images or files 
				incorporated in or generated by the software or data accompanying such 
				software), except that you may download one copy of the Materials on any single 
				computer for your personal, non-commercial use only, provided you keep intact 
				all copyright, trademark and other proprietary notices and make no change in or 
				deletion of author attribution. This limited authorization is not a transfer of 
				title in the Materials and by your use of the Site, you acknowledge that you do 
				not acquire any license, ownership or other rights to the Materials. 
				Modification of the Materials or use of the Materials for any other purpose is 
				a violation of UAL’s copyright, trademark and other proprietary rights and may 
				violate other laws. The use of any such Materials on any other Web site or 
				networked computer or environment is prohibited without UAL’s express written 
				consent. If you breach any of these Terms, your authorization to use the Site 
				automatically terminates and you must immediately destroy any downloaded or 
				printed Materials.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Disclaimer</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				THE SITE AND MATERIALS AND RELATED COMMUNICATIONS ARE PROVIDED "AS IS" WITHOUT 
				ANY REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, OF ANY KIND, INCLUDING, 
				BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILTY, NON-INFRINGEMENT, OR FITNESS 
				FOR PARTICULAR PURPOSE. SOME JURISDICTIONS DO NOT ALLOW FOR THE EXCLUSION OF 
				IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS OF IMPLIED WARRANTIES MAY NOT BE 
				APPLICABLE UNDER CERTAIN CIRCUMSTANCES. UAL ALSO DOES NOT WARRANT THE ACCURACY 
				OR COMPETENESS OF THE MATERIALS, INCLUDING BUT NOT LIMITED TO THE RELIABILITY 
				OF ANY ADVICE, STATEMENT OR OTHER INFORMATION DISPLAYED OR DISTRIBUTED THROUGH 
				THE SITE. YOU ACKNOWLEDGE BY THE USE OF THE SITE THAT ANY RELIANCE ON ANY SUCH 
				MATERIALS, ADVICE, STATEMENT OR INFORMATION SHALL BE AT YOUR SOLE RISK. UAL 
				ASSUMES NO RESPONSIBILITY, AND SHALL NOT BE LIABLE FOR ANY DAMAGES TO, OR 
				VIRUSES THAT MAY INFECT, YOUR COMPUTER EQUIPMENT OR OTHER PROPERTY ON ACCOUNT 
				OF YOUR ACCESS TO, USE OF, OR BROWSING IN THE SITE (INCLUDING ANY BULLETIN 
				BOARD AND CHAT ROOM) OR YOUR DOWNLOADING OF ANY MATERIALS FROM THE SITE.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Limitation of Liability</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				Your use and browsing of the Site is at your risk. If you are dissatisfied with 
				any of the Materials contained in the Site, or with any of these Terms, your 
				sole and exclusive remedy is to discontinue accessing and using the Site.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				UNDER NO CIRCUMSTANCES WILL UAL, ITS SUPPLIERS MENTIONED AT, OR INVOLVED IN 
				CREATING, PRODUCING, OR DELIVERING THE SITE BE LIABLE FOR ANY DIRECT, 
				INCIDENTAL, CONSEQUENTIAL, INDIRECT, SPECIAL OR PUNITIVE DAMAGES WHATSOEVER 
				(INCLUDING WITHOUT LIMITATION, COSTS AND EXPENSES OF ANY TYPE INCURRED, LOST 
				PROFITS, LOST DATA OR PROGRAMS, AND BUSINESS INTERRUPTION) ARISING OUT OF YOUR 
				ACCESS TO, USE, INABILITY TO USE OR THE RESULTS OF USE OF THE SITE, OR ANY 
				MATERIALS CONTAINED AT ANY (INCLUDING BUT NOT LIMITED TO THOSE CAUSED BY OR 
				RESULTING FROM A FAILURE OF PERFORMANCE; ERROR; OMISSION; LINKING TO OTHER WEB 
				SITES; INTERRUPTION; DELETION; DEFECT; DELAY IN OPERATION OR TRANSMISSION; 
				COMPUTER VIRUS; COMMUNICATION LINE FAILURE; OR DESTRUCTION, UNAUTHORIZED ACCESS 
				TO, ALTERATION OF, OR USE OF ANY COMPUTER OR SYSTEM), WHETHER BASED ON 
				WARRANTY, CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER LEGAL 
				THEORY AND WHETHER OR NOT UAL WAS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				UAL SHALL HAVE NO LIABLITY OR RESPONSIBILITY FOR ANY ACTS, OMISSIONS, OR 
				CONDUCT OF ANY USER.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				UAL's obligations and responsibilities regarding its products and services are 
				governed solely by UAL's terms and conditions of sale or license under which 
				such products and services are sold or licensed. Copies of such terms and 
				conditions are available from the applicable UAL entity.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Safe Harbor</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				The Materials at the Site may contain various forward-looking statements and 
				which may be based on or include assumptions, concerning UAL's operations, 
				future results and prospects. These forward-looking statements are based on 
				current expectations and are subject to risk and uncertainties. In connection 
				with the "safe harbor" provisions of the United States' Private Securities 
				Litigation Reform Act of 1995, UAL provides the following cautionary statement 
				identifying important economic, political and technology factors which, among 
				others, could cause the actual results or events to differ materially from 
				those set forth or implied by the forward-looking statements and related 
				assumptions.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				Such factors include the following: (1) changes in the current and future 
				business environment, including interest rates and capital and consumer 
				spending; (2) competitive factors and competitor responses to UAL's 
				initiatives; (3) successful development and market introductions of anticipated 
				products; (4) changes in government laws and regulations, including taxes; (5) 
				unstable governments and business conditions in emerging economies; (6) 
				continuation of the favorable environment to make acquisitions, domestic and 
				foreign, including regulatory requirements and market values of candidates.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Information Provided By You</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				It has been and remains UAL's policy not to accept or consider ideas, 
				suggestions or materials other than those that UAL has specifically requested 
				from you. Accordingly, UAL does not want you to, and you should not, send any 
				confidential or proprietary information to UAL through the Site unless 
				specifically requested by UAL. Please note that any unsolicited information or 
				material sent to UAL will be deemed not to be confidential or proprietary. By 
				submitting information and material to the Site, you automatically grant to UAL 
				(or warrant that the owner of such information and material has expressly 
				granted to UAL) a royalty-free, perpetual, irrevocable, unrestricted, right and 
				license to use, reproduce, display, perform, modify, adapt, publish, translate, 
				transmit and distribute, or otherwise make available to other such information 
				and material (in whole or in part and for any purpose) worldwide and/or to 
				incorporate it in other works in any form, media, or technology now known or 
				hereafter developed. You also agree that UAL is free to use any ideas, 
				concepts, know-how, or techniques that you send UAL for any purpose.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				As further provided above, UAL does not want to receive, and you are deemed to 
				covenant and agree through the use of the Site not to provide, any information 
				or materials to UAL that are defamatory, threatening, obscene, harassing, in 
				violation of any law, governmental requirements or otherwise unlawful, or that 
				incorporate the proprietary information or materials of another person or 
				entity.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				You shall not upload, post or otherwise make available on the Site any 
				information and material protected by copyright, trademark or other proprietary 
				right without the express written permission of the owner of such right(s). You 
				shall be solely liable for any damages resulting from any infringement of 
				copyright, proprietary rights, or any other harm resulting from such a 
				submission.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Changes</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				UAL reserves the right, in its sole discretion, to revise these Terms at any 
				time and correct any errors or omissions in any portion of the Site and 
				Materials. Materials may also be changed, modified, added, or removed and 
				updated without notice at any time; however, UAL is under no obligation to 
				update Materials. UAL may also make changes in the products, services, 
				programs, or prices (if any) described in the Site at any time without notice. 
				Your continued use of the Site after any change UAL makes to the Site will be 
				considered acceptance of those changes. You should revisit these Terms from 
				time to time to review the then-current Terms because they are binding on you.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Linking to Site:</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				Anyone linking to UAL 's Site must comply with UAL 's guidelines for linking to 
				UAL 's Site and all applicable laws.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> International Users</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				The Site is administered by UAL from its offices in the United States. 
				Materials published at the Site may refer to products, programs, or services 
				that are not available in your country. Consult your local UAL business contact 
				in this regard. Furthermore, UAL makes no representation that the Materials at 
				the Site are appropriate or available for use at other locations outside of the 
				United States and access to them from territories where their contents are 
				illegal is prohibited. You may not use the Site or export information and 
				materials in violation of the export laws of the United States or any other 
				country. If you access the Site from a location outside of the United States, 
				you are responsible for compliance with all applicable laws.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Governing Law</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				These Terms shall be governed by the regional laws, without giving effect to 
				any principles of conflicts of law. If any provision of this Agreement and 
				Terms shall be unlawful, void, or for any reason unenforceable then that 
				provision shall be severable from these Terms and shall not affect the validity 
				and enforceability of any remaining provisions. These Terms constitute the 
				entire agreement between UAL and you with respect to your use of the Site. Any 
				cause of action you may have with respect to your use of the Site must be 
				commenced within six (6) months after the claim or cause of action arises.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Privacy:</strong><br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Overview</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				UAL is aware of the need to address Internet privacy issues and we believe you 
				should be aware of how we intend to treat any information about you that we 
				might receive on the Internet as a result of your visit to the Site.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small"><strong> Changes</strong>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				If at anytime UAL changes its privacy commitment, UAL will post those changes 
				here so that you will know what information UAL gathers and how UAL might use 
				that information.<br>
				<br>
			</td>
		</TR>
		<TR>
			<td align="left" class="UAl-text-small">
				© UAC 2005, All Rights Reserved
			</td>
		</TR>
	</TABLE>
</form>
